name: Deploy Files
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Copy style changes to dev branch
        if: github.ref == 'refs/heads/dev'
        run: |
          rsync -uv ./style.css webprod@web-webprod2-dev.cdlib.org:/apps/webprod/apache/htdocs/intracdl/intracdl-dev/wp-content/themes/twentytwentythree
          echo "style changes successfully copied to dev branch"
      - name: Copy style changes to main branch
        if: github.ref == 'refs/heads/main'
        run: |
          rsync -uv ./style.css webprod@web-webprod2-dev.cdlib.org:/apps/webprod/apache/htdocs/intracdl/intracdl-dev/wp-content/themes/twentytwentythree
          echo "style changes successfully copied to main branch"
