name: Deploy Files
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Push changes to dev branch
        if: github.ref == 'refs/heads/dev'
        run: echo "changes successfully pushed to dev branch"
      - name: Push changes to main branch
        if: github.ref == 'refs/heads/main'
        run: echo "changes successfully pushed to main branch"
